/**
 * Standard error codes across the application
 */
export const ERROR_CODES = {
  // ============ VALIDATION ============
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // ============ AUTHENTICATION ============
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_REVOKED: 'TOKEN_REVOKED',

  // ============ OTP ============
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'OTP_MAX_ATTEMPTS_EXCEEDED',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_CHALLENGE_NOT_FOUND: 'OTP_CHALLENGE_NOT_FOUND',

  // ============ USER ============
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_PHONE_TAKEN: 'USER_PHONE_TAKEN',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_DELETED: 'USER_DELETED',

  // ============ AUTHORIZATION ============
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ROLE_REQUIRED: 'ROLE_REQUIRED',

  // ============ RESOURCE ============
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',

  // ============ PROFILE ============
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_NOT_CONFIRMED: 'PROFILE_NOT_CONFIRMED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  INVALID_PROFILE_VERSION: 'INVALID_PROFILE_VERSION',

  // ============ PREFERENCES ============
  PREFERENCES_NOT_FOUND: 'PREFERENCES_NOT_FOUND',
  PREFERENCES_UPDATE_FAILED: 'PREFERENCES_UPDATE_FAILED',

  // ============ ANSWER BANK ============
  ANSWER_NOT_FOUND: 'ANSWER_NOT_FOUND',
  ANSWER_CREATION_FAILED: 'ANSWER_CREATION_FAILED',

  // ============ FILE UPLOAD ============
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  VIRUS_DETECTED: 'VIRUS_DETECTED',

  // ============ ENCRYPTION ============
  ENCRYPTION_FAILED: 'ENCRYPTION_FAILED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',

  // ============ RATE LIMITING ============
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // ============ SERVER ============
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  // ============ CONFIGURATION ============
  MISSING_CONFIG: 'MISSING_CONFIG',
  INVALID_CONFIG: 'INVALID_CONFIG',
};

/**
 * HTTP status codes for errors
 */
export const ERROR_STATUS_CODES: Record<string, number> = {
  VALIDATION_ERROR: 400,
  INVALID_INPUT: 400,
  MISSING_REQUIRED_FIELD: 400,
  UNAUTHORIZED: 401,
  INVALID_CREDENTIALS: 401,
  SESSION_EXPIRED: 401,
  INVALID_TOKEN: 401,
  TOKEN_REVOKED: 401,
  OTP_INVALID: 400,
  OTP_EXPIRED: 400,
  OTP_MAX_ATTEMPTS_EXCEEDED: 429,
  OTP_LOCKED: 429,
  OTP_RESEND_COOLDOWN: 429,
  OTP_RATE_LIMITED: 429,
  OTP_CHALLENGE_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  USER_ALREADY_EXISTS: 409,
  USER_EMAIL_TAKEN: 409,
  USER_PHONE_TAKEN: 409,
  USER_NOT_VERIFIED: 403,
  USER_SUSPENDED: 403,
  USER_DELETED: 404,
  FORBIDDEN: 403,
  INSUFFICIENT_PERMISSIONS: 403,
  ROLE_REQUIRED: 403,
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_CONFLICT: 409,
  RESOURCE_ALREADY_EXISTS: 409,
  PROFILE_NOT_FOUND: 404,
  PROFILE_NOT_CONFIRMED: 400,
  PROFILE_UPDATE_FAILED: 500,
  INVALID_PROFILE_VERSION: 400,
  PREFERENCES_NOT_FOUND: 404,
  PREFERENCES_UPDATE_FAILED: 500,
  ANSWER_NOT_FOUND: 404,
  ANSWER_CREATION_FAILED: 500,
  FILE_UPLOAD_FAILED: 500,
  FILE_TOO_LARGE: 413,
  INVALID_FILE_TYPE: 400,
  VIRUS_DETECTED: 400,
  ENCRYPTION_FAILED: 500,
  DECRYPTION_FAILED: 500,
  RATE_LIMIT_EXCEEDED: 429,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  DATABASE_ERROR: 500,
  EXTERNAL_SERVICE_ERROR: 502,
  MISSING_CONFIG: 500,
  INVALID_CONFIG: 500,
};

/**
 * User-friendly error messages
 */
export const ERROR_MESSAGES: Record<string, string> = {
  VALIDATION_ERROR: 'Invalid input provided.',
  INVALID_INPUT: 'Invalid input provided.',
  MISSING_REQUIRED_FIELD: 'Required field is missing.',
  UNAUTHORIZED: 'Authentication required.',
  INVALID_CREDENTIALS: 'Email, phone, or password is incorrect.',
  SESSION_EXPIRED: 'Your session has expired. Please log in again.',
  INVALID_TOKEN: 'Invalid or malformed token.',
  TOKEN_REVOKED: 'Your session was revoked.',
  OTP_INVALID: 'OTP is incorrect.',
  OTP_EXPIRED: 'OTP has expired.',
  OTP_MAX_ATTEMPTS_EXCEEDED: 'Too many incorrect attempts. Please try again later.',
  OTP_LOCKED: 'Account temporarily locked. Please try again later.',
  OTP_RESEND_COOLDOWN: 'Please wait before requesting a new OTP.',
  OTP_RATE_LIMITED: 'Too many requests. Please try again later.',
  USER_NOT_FOUND: 'User not found.',
  USER_ALREADY_EXISTS: 'User already exists.',
  USER_EMAIL_TAKEN: 'Email is already in use.',
  USER_PHONE_TAKEN: 'Phone number is already in use.',
  USER_NOT_VERIFIED: 'Please verify your email and phone.',
  USER_SUSPENDED: 'Your account has been suspended.',
  USER_DELETED: 'User account was deleted.',
  FORBIDDEN: 'You do not have permission to access this resource.',
  INSUFFICIENT_PERMISSIONS: 'Insufficient permissions.',
  ROLE_REQUIRED: 'Required role is missing.',
  RESOURCE_NOT_FOUND: 'Resource not found.',
  RESOURCE_CONFLICT: 'Resource already exists.',
  PROFILE_NOT_FOUND: 'Profile not found.',
  PROFILE_NOT_CONFIRMED: 'Profile must be confirmed before use.',
  PREFERENCES_NOT_FOUND: 'Preferences not found.',
  ANSWER_NOT_FOUND: 'Answer not found.',
  FILE_UPLOAD_FAILED: 'File upload failed.',
  FILE_TOO_LARGE: 'File is too large.',
  INVALID_FILE_TYPE: 'Invalid file type.',
  VIRUS_DETECTED: 'Virus detected in file.',
  ENCRYPTION_FAILED: 'Encryption failed.',
  DECRYPTION_FAILED: 'Decryption failed.',
  RATE_LIMIT_EXCEEDED: 'Too many requests. Please try again later.',
  INTERNAL_SERVER_ERROR: 'An error occurred. Please try again.',
  SERVICE_UNAVAILABLE: 'Service is temporarily unavailable.',
  DATABASE_ERROR: 'Database error occurred.',
  EXTERNAL_SERVICE_ERROR: 'External service error.',
};
